_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
#  WEIGHTS: "/mnt/data/marie-ai/model_zoo/unilm/dit/dit_base/dit-large-224-p16-500k-d7a2fb.zip"
  WEIGHTS: "/mnt/data/marie-ai/model_zoo/unilm/dit/text_detection/tuned-2500-LARGE-v5-fixed/model_0104999.pth"
  VIT:
    NAME: "dit_large_patch16"
    OUT_FEATURES: [ "layer7", "layer11", "layer15", "layer23" ]
    DROP_PATH: 0.2
  FPN:
    IN_FEATURES: [ "layer7", "layer11", "layer15", "layer23" ]
  ANCHOR_GENERATOR:
    SIZES: [[4], [8], [16], [32], [64]]
    ASPECT_RATIOS: [[1.5, 3.5, 6.5]]
SOLVER:
  WARMUP_ITERS: 1000
  IMS_PER_BATCH: 4
  MAX_ITER: 160000
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.00005
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 1000
  DETECTIONS_PER_IMAGE: 2000

OUTPUT_DIR: $AMLT_OUTPUT_DIR

INPUT:
  MAX_SIZE_TEST: 4000
  MAX_SIZE_TRAIN: 4000
  # MIN_SIZE_TEST: 800
  # MIN_SIZE_TEST: 800
